    call comppas pascal1
    call comppas pascal2
    call comppas pasform
    call comppas paslibx
    call comppas passnap
    call comppas passnapc
    call comppas pasutils
    call compass pasmonn
    call comppas testcein
    call comppas testfile
    call comppas testiein
    call comppas testinp
    call comppas testsna1
    call comppas testsna2
    call comppas testsna3
    call comppas testsqrt
