copy pasmonn.ass        \work\zos_golob\test_neu
copy pasforma.pas       \work\zos_golob\test_neu
copy passcana.pas       \work\zos_golob\test_neu
copy pascal1a.pas       \work\zos_golob\test_neu
copy pascal2a.pas       \work\zos_golob\test_neu
copy PASSNAP.pas        \work\zos_golob\test_neu
copy pasutils.pas       \work\zos_golob\test_neu
copy passcan.pas        \work\zos_golob\test_neu
copy paslibx.pas        \work\zos_golob\test_neu
copy pasform.pas        \work\zos_golob\test_neu
copy PASCAL2.pas        \work\zos_golob\test_neu
copy PASCAL1.pas        \work\zos_golob\test_neu
copy pascal.messages    \work\zos_golob\test_neu

copy showhex.pas        \work\zos_golob\test_neu\test
copy copyteil.pas       \work\zos_golob\test_neu\test
copy comperr2.pas       \work\zos_golob\test_neu\test
copy testrea2.pas       \work\zos_golob\test_neu\test
copy testcopy.pas       \work\zos_golob\test_neu\test
copy xcomp.pas          \work\zos_golob\test_neu\test
copy testrdc.pas        \work\zos_golob\test_neu\test
copy testrea3.pas       \work\zos_golob\test_neu\test
copy testcpy2.pas       \work\zos_golob\test_neu\test
copy testcpy3.pas       \work\zos_golob\test_neu\test
copy testrdd.pas        \work\zos_golob\test_neu\test
copy testrds.pas        \work\zos_golob\test_neu\test
copy testrdv.pas        \work\zos_golob\test_neu\test
copy testrea4.pas       \work\zos_golob\test_neu\test
copy testrea5.pas       \work\zos_golob\test_neu\test
copy testpp.pas         \work\zos_golob\test_neu\test
copy TESTREAD.PAS       \work\zos_golob\test_neu\test
copy testget.pas        \work\zos_golob\test_neu\test
copy testrea6.pas       \work\zos_golob\test_neu\test
copy testrdc2.pas       \work\zos_golob\test_neu\test
copy testrdi2.pas       \work\zos_golob\test_neu\test
copy comperr1.pas       \work\zos_golob\test_neu\test
copy testrdr.pas        \work\zos_golob\test_neu\test
copy testrdi.pas        \work\zos_golob\test_neu\test
copy testhel.pas        \work\zos_golob\test_neu\test
copy testspa.pas        \work\zos_golob\test_neu\test
copy testrs1.pas        \work\zos_golob\test_neu\test
copy testrs2.pas        \work\zos_golob\test_neu\test
copy testerr.pas        \work\zos_golob\test_neu\test
copy testwrb.pas        \work\zos_golob\test_neu\test
copy comperr3.pas       \work\zos_golob\test_neu\test
copy testavl.pas        \work\zos_golob\test_neu\test
copy avltree.pas        \work\zos_golob\test_neu\test
copy rrwcomp.pas        \work\zos_golob\test_neu\test
copy xcompn.pas         \work\zos_golob\test_neu\test
copy testspl.pas        \work\zos_golob\test_neu\test
copy test2.pas          \work\zos_golob\test_neu\test
copy testrdc3.pas       \work\zos_golob\test_neu\test
copy pascals-sam.pas    \work\zos_golob\test_neu\test
copy testset7.pas       \work\zos_golob\test_neu\test
copy testskip.pas       \work\zos_golob\test_neu\test
copy comperr4.pas       \work\zos_golob\test_neu\test
copy cobform.pas        \work\zos_golob\test_neu\test
