copy /y ppbin.cmd        \bin\pp.cmd
copy /y prunbin.cmd      \bin\prun.cmd
copy /y pasfbin.cmd      \bin\pasf.cmd
copy /y pascal1.prr      \bin
copy /y pasform.prr      \bin
copy /y passcan.prr      \bin
copy /y paslibx.prr      \bin
copy /y pasutils.prr     \bin
copy /y passcan.pas      \bin
copy /y paslibx.pas      \bin
copy /y pasutils.pas     \bin
copy /y pascal.messages  \bin
copy /y pcint.exe        \bin
