    call copymvs pascal1.pas   compiler.pas
    call copymvs pascal1a.pas  compiler.pas
    call copymvs pascal1b.pas  compiler.pas
    call copymvs pascal2.pas   compiler.pas
    call copymvs pascal2a.pas  compiler.pas
    call copymvs pascal2b.pas  compiler.pas
    call copymvs pasform.pas   compiler.pas
    call copymvs pasforma.pas  compiler.pas
    call copymvs paslibx.pas   compiler.pas
    call copymvs passcan.pas   compiler.pas
    call copymvs passcana.pas   compiler.pas
    call copymvs passnap.pas   compiler.pas
    call copymvs passnapc.pas  compiler.pas
    call copymvs pasutils.pas  compiler.pas
