rem call toexec movev
rem call toexec pascompa
rem call toexec pascompn
rem call toexec pasf
rem call toexec pasformf
rem call toexec pasformt
rem call toexec pasfsqlt
rem call toexec paslink
rem call toexec paslinkc
rem call toexec pasprod
rem call toexec pasrun
rem call toexec pasrunc
rem call toexec pasrunm
rem call toexec pcodeaaa
rem call toexec pcodennn
rem call toexec pformat
rem call toexec plicomp
rem call toexec plilink
rem call toexec pp
rem call toexec ppa
rem call toexec ppc
rem call toexec ppca
rem call toexec ppm
rem call toexec profile
    call toexec progtest
rem call toexec prun
rem call toexec prunc
rem call toexec prunm
rem call toexec pr
rem call toexec pu
