program TESTDUPL ( INPUT , OUTPUT ) ;


type SUBR = 0 .. 30 ;


var VARIABLE_H_LANGER_NAME : INTEGER ;
    VARIABLE_H_LANGER_ANDERER_NAME : INTEGER ;



procedure PROC_LANGER_NAME_2 ;

   var VARIABLE_2_LANGER_NAME : INTEGER ;
       VARIABLE_2_LANGER_ANDERER_NAME : INTEGER ;
       X : SUBR ;

   begin (* PROC_LANGER_NAME_2 *)
     VARIABLE_2_LANGER_NAME := 7 ;
     VARIABLE_2_LANGER_ANDERER_NAME := 23 ;
     X := 27 ;
     X := X + 5 ;
   end (* PROC_LANGER_NAME_2 *) ;



procedure PROC_LANGER_NAME_1 ;

   var VARIABLE_1_LANGER_NAME : INTEGER ;
       VARIABLE_1_LANGER_ANDERER_NAME : INTEGER ;

   begin (* PROC_LANGER_NAME_1 *)
     VARIABLE_1_LANGER_NAME := 11 ;
     VARIABLE_1_LANGER_ANDERER_NAME := 27 ;
     PROC_LANGER_NAME_2 ;
   end (* PROC_LANGER_NAME_1 *) ;



begin (* HAUPTPROGRAMM *)
  VARIABLE_H_LANGER_NAME := 5 ;
  VARIABLE_H_LANGER_ANDERER_NAME := 12 ;
  WRITELN ( VARIABLE_H_LANGER_NAME ) ;
  WRITELN ( VARIABLE_H_LANGER_ANDERER_NAME ) ;
  PROC_LANGER_NAME_1 ;
end (* HAUPTPROGRAMM *) .
