copy /y ppbin.cmd        \bin\pp.cmd
copy /y prunbin.cmd      \bin\prun.cmd
copy /y prundbin.cmd     \bin\prund.cmd
copy /y pasfbin.cmd      \bin\pasf.cmd
copy /y pascal1.pcode    \bin
copy /y pascal1.pcode1   \bin
copy /y pasform.pcode    \bin
copy /y passcan.pcode    \bin
copy /y paslibx.pcode    \bin
copy /y pasutils.pcode   \bin
copy /y passcan.pas      \bin
copy /y paslibx.pas      \bin
copy /y pasutils.pas     \bin
copy /y pascal.messages  \bin
copy /y pcint.exe        \bin
