call copymvs pasalloc.job  compiler.cntl
call copymvs pasdel.job    compiler.cntl
call copymvs pasdown1.job  compiler.cntl
call copymvs pasdown2.job  compiler.cntl
call copymvs pasdown3.job  compiler.cntl
call copymvs pasinst1.job  compiler.cntl
call copymvs pasinst2.job  compiler.cntl
call copymvs pasload1.job  compiler.cntl
call copymvs pasload2.job  compiler.cntl
call copymvs pasload3.job  compiler.cntl
